### ISSUE TITLE
AttributeError: module 'PyQt5.QtCore' has no attribute 'SIGNAL'

### ISSUE THREAD

**Issue by wittrup** [picotech/picosdk-python-examples#2]
Hi

After installing PyQt5 and pyqtgraph, I ran into this error when running [picopyscope.py](https://github.com/picotech/picosdk-python-examples/blob/master/python-picoscope/picopyscope.py):

```python
Traceback (most recent call last):
  File "C:/Users/wittrup/Documents/GitHub/picosdk-python-examples/python-picoscope/picopyscope.py", line 155, in <module>
    class PicoPyDeviceWorker(QtCore.QObject):
  File "C:/Users/wittrup/Documents/GitHub/picosdk-python-examples/python-picoscope/picopyscope.py", line 156, in PicoPyDeviceWorker
    finished = QtCore.SIGNAL("finished")
AttributeError: module 'PyQt5.QtCore' has no attribute 'SIGNAL'
```

How to remedy this error?

**Comment by hsmistry** [comment]
Hi @wittrup, try installing the [Python(x,y)](https://python-xy.github.io/) suite as per the README.

**Comment by wittrup** [comment]
Error still persist after installing [Python(x,y)](https://python-xy.github.io/) suite.

**Comment by klanclos** [comment]
> PyQt4’s old-style signals and slots are not supported. Therefore the following are not implemented in PyQt5:
>
>    QObject.connect()
>    QObject.emit()
>    SIGNAL()
>    SLOT()
>
> All methods that had arguments that are usually the results of calls to SIGNAL() or SLOT() are no longer supported. There will always be an equivalent that takes a bound signal or callable respectively.

http://pyqt.sourceforge.net/Docs/PyQt5/pyqt4_differences.html
