### ISSUE TITLE
Rapid Block Mode

### ISSUE THREAD

**Issue by IonutGorgos** [picotech/picosdk-python-examples#5]
### Setup

* Example filename: Any
* Version of Python: 2.7
* Pico Technology device model: 6404D
* Driver name and version number: PS6000 Linux Driver, 1.7.0.10
* Operating system: Ubuntu 16.04
* USB port type	(e.g. 2.0): 3.0

### Description
Hi,
How can I use this library for the rapid block mode? I read the section 2.5.2 from Picoscope 6000 Series Programmers Guide, but in this library some methods are not implemented. I already tried the Pico-Python Library [1], but I have some problems with the rapid block mode (I get some random data, not waveforms). The problems persists on Windows, Linux and MacOs, and I have no idea what to do. 

I want to try this library to see if the problem persists, but I don't know how to use rapid block mode.
Thanks

[1] - https://github.com/colinoflynn/pico-python/

**Comment by hsmistry** [comment]
@IonutGorgos, your e-mail support request has been received. I will respond via that and provide an update here.

Thanks,
